import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { loadPokemons } from "../lib";

const Home: NextPage = ({ allPokemons }: any) => {
  return (
    <div>
      <Head>
        <title>Pokemon Searcher | Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Search a Pokemon!
        </h1>
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  const res = await loadPokemons();
  const allPokemons = await res.results;
  return {
    props: {
      allPokemons,
    },
  };
};

export default Home;
