import {
  Button,
  Container,
  Heading,
  Input,
  SimpleGrid,
  Stack,
  Text,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { loadPokemons } from "../lib";

const Home: NextPage = ({ allPokemons }: any) => {
  const handleSearch = (e: any) => {
    console.log(e.target.value.toLowerCase());
  };

  return (
    <div>
      <Head>
        <title>Pokemon Searcher | Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/star-poke.ico" />
      </Head>

      <Container maxW="1280px" backgroundColor="tomato">
        <Stack spacing={4}>
          <Heading textAlign="center">Search a Pokemon!</Heading>

          <Stack width="100%" p="0 2rem">
            <Input
              w="100%"
              type="text"
              placeholder="Busca un pokemon"
              onChange={(e) => handleSearch(e)}
            />
          </Stack>

          {/* Cards container */}
          <Stack>
            <SimpleGrid minChildWidth="140px" spacing="20px">
              {allPokemons?.map((poke: any, index: any) => (
                <Stack key={index} bg="blue" p={1}>
                  <Text>{index + 1}</Text>
                  <Text textAlign="center" p={0} m={0}>
                    {poke.name.charAt(0).toUpperCase() + poke.name.slice(1)}
                  </Text>
                  <Stack align="center">
                    <Stack>
                      <Image
                        unoptimized
                        src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${
                          index + 1
                        }.png`}
                        width={100}
                        height={100}
                        alt={poke.name}
                        objectFit="contain"
                      />
                    </Stack>
                    <Stack></Stack>
                    <Stack>
                      <Text>Description</Text>
                    </Stack>
                  </Stack>
                </Stack>
              ))}
            </SimpleGrid>
          </Stack>
        </Stack>
      </Container>
    </div>
  );
};

export const getStaticProps = async () => {
  const res = await loadPokemons();
  const allPokemons = await res.results;
  return {
    props: {
      allPokemons,
    },
  };
};

export default Home;
